<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="idmDay" nsURI="http://www.lig.fr/vasco/IdmDay" nsPrefix="idmDay">
  <eClassifiers xsi:type="ecore:EClass" name="IdmDayModel">
    <eAnnotations source="meeduse">
      <details key="generated" value="NOT"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="meeduse">
        <details key="generated" value="NOT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1"
        eType="#//Section" containment="true">
      <eAnnotations source="meeduse">
        <details key="generated" value="NOT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trains" upperBound="-1"
        eType="#//Train" containment="true">
      <eAnnotations source="meeduse">
        <details key="generated" value="OK"/>
        <details key="association" value="trains"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="meeduse">
        <details key="generated" value="NOT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" lowerBound="1" eType="#//Section">
      <eAnnotations source="meeduse">
        <details key="association" value="next"/>
        <details key="opposite" value="previous"/>
        <details key="opposite-lower" value="1"/>
        <details key="opposite-upper" value="1"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" upperBound="-1"
        eType="#//Train">
      <eAnnotations source="meeduse">
        <details key="association" value="position"/>
        <details key="opposite" value="section"/>
        <details key="opposite-lower" value="1"/>
        <details key="opposite-upper" value="1"/>
        <details key="opposite-navigable" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Train">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="meeduse">
        <details key="generated" value="NOT"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
