<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gpuScheduler" nsURI="http://www.lig.fr/vasco/GpuScheduler" nsPrefix="gpuScheduler">
  <eClassifiers xsi:type="ecore:EClass" name="Server">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="meeduse">
        <details key="generated" value="NOT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gpus" upperBound="-1" eType="#//Gpu"
        containment="true">
      <eAnnotations source="meeduse">
        <details key="association" value="gpus"/>
        <details key="opposite-upper" value="1"/>
        <details key="opposite-lower" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pocesses" upperBound="-1"
        eType="#//Process" containment="true">
      <eAnnotations source="meeduse">
        <details key="association" value="processes"/>
        <details key="opposite-upper" value="1"/>
        <details key="opposite-lower" value="0"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gpu">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="meeduse">
        <details key="generated" value="NOT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedBy" upperBound="-1"
        eType="#//Process">
      <eAnnotations source="meeduse">
        <details key="association" value="running"/>
        <details key="opposite-upper" value="1"/>
        <details key="opposite-lower" value="0"/>
        <details key="opposite-navigable" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="meeduse">
        <details key="generated" value="NOT"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
