<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="schedularDSL2" nsURI="http://www.example.org/schedularDSL2"
    nsPrefix="schedularDSL2">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="schedular">
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" upperBound="-1"
        eType="#//Process" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Number" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Status" eType="#//StatusEnum">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="{&#xA;initial:&#xA;Process.allInstances()->&#xA;iterate(elem : Process; acc : Integer = 1 |&#xA;if elem.Number > acc then&#xA;acc&#xA;else&#xA;elem.Number&#xA;endif&#xA;) + 1 ;&#xA;}"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StatusEnum">
    <eLiterals name="waitingDSL"/>
    <eLiterals name="readyDSL" value="1"/>
    <eLiterals name="activeDSL" value="2"/>
  </eClassifiers>
</ecore:EPackage>
