<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="liftM" nsURI="http://www.example.org/liftM" nsPrefix="liftM">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Lift">
    <eAnnotations source="meeduse">
      <details key="generated" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="meeduse">
        <details key="generated" value="NOT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="liftPosition" lowerBound="1"
        eType="#//Floor" eOpposite="#//Floor/lift">
      <eAnnotations source="meeduse">
        <details key="generated" value=""/>
        <details key="association" value="liftPosition"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Direction" lowerBound="1"
        eType="#//LiftDirection">
      <eAnnotations source="meeduse">
        <details key="generated" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Door" lowerBound="1" eType="#//DoorStatus">
      <eAnnotations source="meeduse">
        <details key="generated" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedFloors" upperBound="-1"
        eType="#//Floor" eOpposite="#//Floor/selecterLift">
      <eAnnotations source="meeduse">
        <details key="generated" value=""/>
        <details key="association" value="selectedFloors"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Floor">
    <eAnnotations source="meeduse">
      <details key="generated" value=""/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="meeduse">
        <details key="generated" value="NOT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lift" upperBound="-1" eType="#//Lift"
        eOpposite="#//Lift/liftPosition">
      <eAnnotations source="meeduse">
        <details key="generated" value=""/>
        <details key="association" value="liftPosition"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="up" eType="#//Floor" eOpposite="#//Floor/down">
      <eAnnotations source="meeduse">
        <details key="association" value="up_down"/>
        <details key="generated" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="down" eType="#//Floor"
        eOpposite="#//Floor/up">
      <eAnnotations source="meeduse">
        <details key="association" value="up_down"/>
        <details key="generated" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cabins" upperBound="-1"
        eType="#//Cabin" containment="true" eOpposite="#//Cabin/floor">
      <eAnnotations source="meeduse">
        <details key="generated" value="NOT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selecterLift" upperBound="-1"
        eType="#//Lift" eOpposite="#//Lift/selectedFloors">
      <eAnnotations source="meeduse">
        <details key="generated" value="NOT"/>
        <details key="association" value="selectedFloors"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Building" abstract="true">
    <eAnnotations source="meeduse">
      <details key="generated" value="NOT"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="floors" upperBound="-1"
        eType="#//Floor" containment="true">
      <eAnnotations source="meeduse">
        <details key="association" value="building_floors"/>
        <details key="generated" value="NOT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lifts" upperBound="-1"
        eType="#//Lift" containment="true">
      <eAnnotations source="meeduse">
        <details key="generated" value="NOT"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LiftDirection">
    <eAnnotations source="meeduse">
      <details key="generated" value=""/>
    </eAnnotations>
    <eLiterals name="Up"/>
    <eLiterals name="Down" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DoorStatus">
    <eAnnotations source="meeduse">
      <details key="generated" value=""/>
    </eAnnotations>
    <eLiterals name="Closed"/>
    <eLiterals name="Open" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cabin">
    <eAnnotations source="meeduse">
      <details key="generated" value="NOT"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="meeduse">
        <details key="generated" value="NOT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongsTo" lowerBound="1"
        eType="#//Lift">
      <eAnnotations source="meeduse">
        <details key="generated" value="NOT"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="floor" lowerBound="1" eType="#//Floor"
        eOpposite="#//Floor/cabins">
      <eAnnotations source="meeduse">
        <details key="generated" value="NOT"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
